[package]
name = "rs-timestamp2arrow"
version = "0.1.0"
edition = "2024"

[dependencies.arrow]
version = "56"
default-features = false
features = [
]

[dependencies.chrono]
version = "0"
default-features = false
features = [
	"std",
]
